name: Nickfost
favicon: null
layout_spectrum: 1
typography_spectrum: 0.49518
title: Nickfost
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6902214251458645
  lightness: 0.530641372082755
  saturation: 0.5707435084041208
  rhythmicContrast: 0.27533555193804204
purpose: []
